spring:
  application:
    name: NEXORA-BACKEND
  data:
    mongodb:
      uri: ${MONGODB_URL:mongodb://username:password@localhost:27018/nexora?authSource=admin}
      auto-index-creation: true
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_BROKERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: reactive-audit-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
    listener:
      ack-mode: manual

server:
  port: ${PORT:9001}

app:
  security:
    opa-base-url: ${OPA_BASE_URL:http://localhost:8181}
    internal-access-token: ${INTERNAL_ACCESS_TOKEN:internalAccessToken123}
    un-secured-path:
      - "/users/register"
      - "/iam/accounts/register"
      - "/iam/accounts/authenticate"
      - "/iam/sessions/validate"
      - "/iam/sessions/refresh"
    iam-base-url: ${IAM_BASE_URL:http://localhost:${server.port}}
    jwt:
      secret: ${JWT_SECRET:secret}
  zone:
    base-url: ${ZONE_BASE_URL:http://localhost:${server.port}}