name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3.0.0
        with:
          java-version: '21'
          distribution: zulu

      - name: Unit test
        run: ./gradlew clean test

#      - name: Build with Gradle
#        uses: gradle/gradle-build-action@v2
#        with:
#          gradle-version: '8.10'
#          arguments: build
#        env:
#          USERNAME: ${{ secrets.ACTOR }}
#          TOKEN: ${{ secrets.PAT_TOKEN }}

#      - name: Docker login
#        run: |
#          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
#          docker buildx create --use
#          docker buildx inspect --bootstrap
#
#      - name: Docker build and push
#        run: bash ./build.sh